# Step 1: Use the official Node.js image as the base image
FROM node:18-alpine

# Step 2: Set the working directory inside the container
WORKDIR /app

# Step 3: Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Step 4: Install dependencies
RUN npm install --production

# Step 5: Copy the rest of the application code to the working directory
COPY . .

# Step 6: Expose the port on which your Node.js app will run (default is 3000)
EXPOSE 5000

# Step 7: Define the command to run your app
CMD ["node", "server.js"]
